apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: nginx-test
    namespace: argocd #(this is the namespace where the argocd is present)
spec:
  project: test-project  # this is the name of the project 
  source:
    repoURL: https://github.com/mechatron10/ArgoCD.git # this is the url of the repository where the manifests are present
    targetRevision: HEAD  # commit of the repo which will be used to refer to the manifests
    path: ./app-config/manifests/ # path of the manifests files inside the repository 
  destination:
    server: https://kubernetes.default.svc # cluster url, for local cluster it is https://kubernetes.default.svc
    namespace: application # it is the namespace where the application will be deployed
  syncPolicy:
    automated:
      prune: true # use this to enable pruning
      selfHeal: true # enable this option to let the selfHeal be running and available.		