apiVersion: v1 
kind : ConfigMap
metadata:
  name: syncwaves-configmap
  namespace: syncwaves
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  index.html: |
    <html>
    <head>
        <title>Sync Waves</title>
    </head>
    <body>
        <h1>Welcome to Sync Waves!</h1>
        <p>This is a sample application to demonstrate ArgoCD Sync Waves.</p>
    </body>
    </html>