apiVersion: v1
kind: Service
metadata:
  name: "sync-waves-service"
  namespace : "syncwaves"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: "sync-waves"
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 80